# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# gpg-agent
export SSH_AUTH_SOCK=$(gpgconf --list-dirs agent-ssh-socket)
gpgconf --launch gpg-agent

# Disable SHARE_HISTORY enabled by prezto history module
unsetopt SHARE_HISTORY

# aliases
alias l='ls'
alias la='ls -a'
alias ll='ls -l'
alias lla='ls -la'
alias lm='lla | "$PAGER"'

alias -g L='|less'
alias pass='gopass'
alias p='pass'
alias pc='pass -c'

# key mappings
bindkey "^[^[[C"  forward-word              # alt + right
bindkey "^[^[[D"  backward-word             # alt + left
bindkey "^[^[[A"  _history-complete-older   # alt + up
bindkey "^[^[[B"  _history-complete-newer   # alt + down

