#!/bin/sh
#
# Install homebrew packages
#
# Authors:
#   <tsv@gmail.com>
#
#

# Check for Homebrew
if test ! $(which brew); then
  echo "You should probably install Homebrew first:"
  echo "  https://github.com/mxcl/homebrew/wiki/installation"
  exit
fi

# Install core packages
brew install lesspipe
brew install htop
brew install wget
brew install git

# Should be installed last to make sure user will read messages from
# about manual postinstall actions required to use zsh
brew install --disable-etcdir zsh
