#!/usr/bin/env sh
# Install homebrew packages

# Check for Homebrew
if test ! $(which brew); then
  echo "You should probably install Homebrew first:"
  echo "  https://github.com/mxcl/homebrew/wiki/installation"
  exit
fi

# Install core packages
brew install lesspipe
brew install htop
brew install wget
brew install git
brew install fasd
brew install macvim
brew install mc
brew install unrar
brew install exiftool
brew install terminal-notifier

# Install tmux
brew install tmux
brew install reattach-to-user-namespace

# Install screen with 256 color support
brew tap homebrew/dupes
brew install screen

# Should be installed last to make sure user will read messages
# about manual postinstall actions required to use zsh
brew install zsh
