#!/usr/bin/env sh
# Install homebrew packages

# Check for Homebrew
if test ! $(which brew); then
  read -p "Confirm installing Homebrew (y/n): [n]" -n 1 -r; echo
  if [ "$REPLY" = "y" ]; then
    ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
  else
    exit
  fi
fi

# Install Cask
brew install caskroom/cask/brew-cask
brew tap caskroom/versions

# Install core packages
brew install lesspipe
brew install htop
brew install wget
brew install git
brew install fasd
brew install exiftool
brew install terminal-notifier
brew install the_silver_searcher
brew install watch
brew install pass
brew install p7zip
brew install jsonpp
brew install jq
brew install lnav
brew install ssh-copy-id

# Install tmux
brew install tmux
brew install reattach-to-user-namespace

# Should be installed last to make sure user will read messages
# about manual postinstall actions required to use zsh
brew install zsh
