#!/usr/bin/env sh
# Install homebrew packages for web development system

# Install php
# NB! /etc/httpd.conf should be manually updated to load new libphp5.so
brew tap homebrew/dupes
brew tap josegonzalez/homebrew-php
brew install php55
brew install composer

# Pear packages
pear install PHP_CodeSniffer

# Install node
brew install node

# Install node dev packages
npm install -g grunt-cli
npm install -g less
npm install -g bower
