name: Dotfiles CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: actions/checkout@v3
    - name: Test dotfiles in docker
      run: make docker-test
    - name: Collect ztime artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ztime
        path: ci-artifacts/ztime
    - name: Collect zprof artifacts
      uses: actions/upload-artifact@v3
      with:
        name: zprof
        path: ci-artifacts/zprof
    - uses: mshick/add-pr-comment@v2
      with:
        message-path: |
          ci-artifacts/ztime
