name: Dotfiles CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-ubuntu:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v2
    - uses: docker/build-push-action@v4
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        load: true
        context: .
        tags: zsh-dotfiles-test
    - name: Test dotfiles in docker
      run: make docker-test
    - name: Collect ztime artifacts
      uses: actions/upload-artifact@v3
      with:
        name: ztime
        path: ci-artifacts/ztime
    - name: Collect zprof artifacts
      uses: actions/upload-artifact@v3
      with:
        name: zprof
        path: ci-artifacts/zprof
    - uses: mshick/add-pr-comment@v2
      if: ${{ github.event_name == 'pull_request' }}
      with:
        allow-repeats: true
        preformatted: true
        message-path: |
          ci-artifacts/ztime_avg
  test-macOS:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Clean workspace
        run: rm -f ~/.gitconfig

      - name: Cache Homebrew Packages
        id: cache-homebrew-packages
        uses: actions/cache@v3
        env:
          cache-name: homebrew-packages
        with:
          path: $(brew --prefix)
          key: ${{ hashFiles('macOS/required/Brewfile') }}

      - name: Test dotfiles
        run: |
          brew bundle --file=macOS/required/Brewfile
          make test

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: macos
          path: ci-artifacts