name: Dotfiles CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  test-docker:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v3
    - uses: docker/setup-buildx-action@v2
      with:
        install: true

    - name: Assemble container image name
      id: image-name
      run: |
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        [ "$VERSION" == "master" ] && VERSION=latest
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        echo "name=$IMAGE_ID:$VERSION\n" >> $GITHUB_OUTPUT
      env:
        IMAGE_ID: dotfiles

    - name: Build and push demo container image to registry
      uses: docker/build-push-action@v4
      with:
        cache-from: type=gha
        cache-to: type=gha,mode=max
        push: true
        context: .
        tags: ghcr.io/${{ github.repository_owner }}/dotfiles:${{ steps.image-name.outputs.name }}

    - name: Test dotfiles in docker
      run: make docker-test

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: docker
        path: ci-artifacts

    - name: Log in to ghcr.io registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

    - name: Push container image to registry
      run: |
        IMAGE_NAME=dotfiles
        IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
        IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
        VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
        [ "$VERSION" == "master" ] && VERSION=latest
        echo IMAGE_ID=$IMAGE_ID
        echo VERSION=$VERSION
        docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:$VERSION

  test-macOS:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3

    - name: Clean workspace
      run: rm -f ~/.gitconfig

    - name: Test dotfiles
      run: |
        make homebrew-required
        make test

    - name: Upload artifacts
      uses: actions/upload-artifact@v3
      with:
        name: macOS
        path: ci-artifacts

  publish-pr-comment:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    needs: [test-docker, test-macOS]
    permissions:
      pull-requests: write

    steps:

    - name: Download artifacts
      uses: actions/download-artifact@v3
      with:
        path: artifacts

    - name: Assemble PR comment message
      run: |
        echo -n > comment
        cd artifacts
        {
          for d in *; do
            echo \# $d
            echo '```'
            cat $d/ztime_avg
            echo
            cat $d/ztime
            echo '```'
          done
        } 2>&1 >> ../comment

    - name: Add PR comment
      uses: mshick/add-pr-comment@v2
      if: ${{ github.event_name == 'pull_request' }}
      with:
        allow-repeats: true
        message-path: comment
